### ISSUE TITLE
sally needs to be noticed.

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/sally#40]
It needs an install target.

**Comment by ianamason** [comment]
6bd238351e4f0fe479f1135f1bca802ff260cffd

**Comment by dddejan** [comment]
I didn't do this because this simple solution doesn't work. There are libraries that need to somehow be included in the install. For example this simple solution results in the following.

```
dejan@hilbert:~$ ~/Software/bin/sally 
/home/dejan/Software/bin/sally: error while loading shared libraries: libyices.so.2.5: cannot open shared object file: No such file or directory
```

Even if I set the LD_LIBRARY_FLAGS to where yices is (which I shouldn't have to), then I get 

```
dejan@hilbert:~$ ~/Software/bin/sally 
/home/dejan/Software/bin/sally: error while loading shared libraries: libantlr3c.so: cannot open shared object file: No such file or directory
```

Usually, when doing a ``make install``, it should write in the binary which libraries it's using (e.g. yices2). And, for the libraries that it's making it should also install them (e.g. the libantlr library).

**Comment by ianamason** [comment]
yes ok. back to the drawing board.

**Comment by dddejan** [comment]
I just commited something, can you check if it works on a mac.

**Comment by ianamason** [comment]
Works on my mac as well as Bruno's.
